### ISSUE TITLE
missing log events

### ISSUE THREAD

**Issue by oboehm** [netmikey/logunit#7]
I want to test Log4J2 messages and use logunit-core together with logunit-log4j2 (v2.0.0). Here is my test class:

```
import io.github.netmikey.logunit.api.LogCapturer;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.MethodName.class)
class LogTest {

    @RegisterExtension
    LogCapturer logCapturer = LogCapturer.create().captureForType(LogTest.class);

    private static final Logger log = LoggerFactory.getLogger(LogTest.class);

    @BeforeEach
    void createLog() {
        log.info("Test-Log created.");
    }

    @Test
    void getEvents() {
        //log.info("Get events.");
        assertFalse(logCapturer.getEvents().isEmpty());
    }

    @Test
    void testMessage() {
        //log.info("Test message.");
        logCapturer.assertContains("Test");
    }

}
```

I see the log ("Test-Log created.") but the tests fail. This is the same problem I have with real tests. Only in some cases the events are not empty.

**Comment by netmikey** [comment]
That's because you're trying to capture logs that have been written outside the `@Test`-annotated method. This is not how LogUnit is intended to be used. It is intended to capture logs that are written by the unit-under-test, not the unit test itself. The unit / class under test's functionality is usually tested in the `@Test`-annotated method and that's what triggers it to write logs.

In other, more technical terms: LogUnit uses JUnit's [`BeforeTestExecutionCallback`](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/extension/BeforeTestExecutionCallback.html) and [`AfterTestExecutionCallback`](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/extension/AfterTestExecutionCallback.html) mechanism to hook into the JUnit test lifecycle and set itself up in the logging framework. The JUnit documentation states:

> Such callbacks will be invoked after any user defined setup methods (e.g., [@BeforeEach](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/BeforeEach.html) methods).

This means LogUnit isn't hooked into the logging framework during the `@Before*` methods.
